apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "mongodb.namespace" . }}
  name: mongodb-config
  labels:
    app.kubernetes.io/name: {{ include "mongodb.name" . }}
    helm.sh/chart: {{ include "mongodb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  host: {{ include "mongodb.fullname" . }}
