{{- $fullname := include "mongodb.fullname" . -}}
{{- $mongoUrl :=  printf "%s%s" "mongodb://" $fullname -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ include "mongodb.namespace" . }}
  name: mongodb-secret
  labels:
    app.kubernetes.io/name: {{ include "mongodb.name" . }}
    helm.sh/chart: {{ include "mongodb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  url: {{ $mongoUrl | b64enc }}
