apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: {{ include "mongodb.namespace" . }}
  name: {{ include "mongodb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mongodb.name" . }}
    helm.sh/chart: {{ include "mongodb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "mongodb.fullname" . }}
  replicas: {{ .Values.deployment.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mongodb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.container }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range .ports }}
            - name: {{ .name | default "http" }}
              protocol: {{ .protocol | default "TCP" }}
              containerPort: {{ .containerPort }}
            {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ required "volumeMounts.name is required" .name }}
              mountPath: {{ required "volumeMounts.mountPath is required" .mountPath }}
            {{- end }}
      restartPolicy: {{ .restartPolicy | default "Always" }}
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds | default 30 }}
      {{- end }}
  {{- with .Values.deployment }}
    {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  replicas: {{ .replicaCount | default 1 }}
  revisionHistoryLimit: {{ .revisionHistoryLimit | default 0 }}
  volumeClaimTemplates:
  {{- range .volumeClaimTemplates }}
  - metadata:
      name: {{ required "volumeClaimTemplates.name is required" .name }}
    spec:
      {{- if .storageClassName }}
      {{- if (eq "-" .storageClassName) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .storageClassName }}"
      {{- end }}
      {{- end }}
      accessModes: {{ .accessModes | default "[ ReadWriteOnce ]" }}
      resources:
        requests:
          storage: {{ required "volumeClaimTemplates.storage is required" .storage }}
{{- end }}
  {{- end }}
