{{- $fullname := include "mongo-express.fullname" . -}}
{{- $mongodbConfigMapName := required "mongodb.configMapName global variable is missing" .Values.global.mongodb.configMapName -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "mongo-express.namespace" . }}
  name: {{ include "mongo-express.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mongo-express.name" . }}
    helm.sh/chart: {{ include "mongo-express.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mongo-express.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mongo-express.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.container }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $fullname }}-credentials
                  key: username
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullname }}-credentials
                  key: password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ $mongodbConfigMapName }}
                  key: host
          ports:
            {{- range .ports }}
            - name: {{ .name | default "http" }}
              protocol: {{ .protocol | default "TCP" }}
              containerPort: {{ .containerPort }}
            {{- end }}
          {{- with .livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: {{ .restartPolicy | default "Always" }}
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds | default 30 }}
      {{- end }}
  {{- with .Values.deployment }}
    {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  replicas: {{ .replicaCount | default 1 }}
  revisionHistoryLimit: {{ .revisionHistoryLimit | default 0 }}
  volumeClaimTemplates:
  {{- range .volumeClaimTemplates }}
    - metadata:
        name: {{ required "volumeClaimTemplate name is missing" .name }}
      spec:
        {{- if .storageClassName }}
        {{- if (eq "-" .storageClassName) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .storageClassName }}"
        {{- end }}
        {{- end }}
        accessModes: {{ .accessModes | default "[ ReadWriteOnce ]" }}
        resources:
          requests:
            storage: {{ required "volumeClaimTemplate storage is missing" .storage }}
  {{- end }}
  {{- end }}
