apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ include "mongo-express.namespace" . }}
  name: {{ include "mongo-express.fullname" . }}-credentials
data:
  username: {{ .Values.application.username | b64enc }}
  password: {{ .Values.application.password | b64enc }}
