apiVersion: v2
appVersion: "1.0"
version: 1.0.0
name: orchestrator
description: Orchestrator chart in Helm/Kubernetes
dependencies:
- name: cert-manager
  version: 0.13.1
  repository: "@jetstack"
  tags:
    - cert-manager
- name: cert-manager-customizations
  version: 1.0.0
  repository: file://../cert-manager-customizations
  tags:
    - cert-manager
- name: hello
  version: 1.0.0
  repository: file://../hello
  alias: experiment-hello
  tags:
    - experiment
- name: links
  version: 1.0.0
  repository: file://../links
  tags:
    - links
- name: mongodb
  version: 1.0.0
  repository: file://../mongodb
  tags:
    - mongodb
- name: mongo-express
  version: 1.0.0
  repository: file://../mongo-express
  tags:
    - mongodb
- name: nginx-ingress
  # https://github.com/helm/charts/blob/master/stable/nginx-ingress/Chart.yaml
  version: 1.41.x
  repository: "@stable"
  tags:
    - nginx-ingress
- name: prometheus-operator
  # https://github.com/helm/charts/blob/master/stable/prometheus-operator/Chart.yaml
  version: 8.x.x
  repository: "@stable"
  tags:
    - prometheus-operator
- name: prometheus-blackbox-exporter
  # https://github.com/helm/charts/blob/master/stable/prometheus-blackbox-exporter/Chart.yaml
  version: 3.x.x
  repository: "@stable"
  tags:
    - prometheus-addons
- name: prometheus-pushgateway
  # https://github.com/helm/charts/blob/master/stable/prometheus-pushgateway/Chart.yaml
  version: 1.x.x
  repository: "@stable"
  tags:
    - prometheus-addons
