tags:
  experiment: true
  nginx-ingress: true
  mongodb: true

####################
# Global variables #
####################

global:
  mongodb:
    configMapName: mongodb-config
    secretName: mongodb-secret

####################
# Experiment hello #
####################

experiment-hello:
  fullnameOverride: experiment-hello

###########
# MongoDB #
###########

mongodb:
  fullnameOverride: "mongodb"

#################
# Mongo express #
#################

mongo-express:
  fullnameOverride: "mongo-express"
