tags:
  cert-manager: false
  experiment: false
  links: false
  mongodb: false
  nginx-ingress: false
  prometheus-operator: false
  prometheus-addons: false

####################
# Global variables #
####################

global:
  default:
    ingress:
      issuer:
        name: cm-cluster-issuer-letsencrypt-staging
        type: cluster-issuer

