apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "<CHARTNAME>.namespace" . }}
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "<CHARTNAME>.name" . }}
    helm.sh/chart: {{ include "<CHARTNAME>.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  # Add your key value pairs here
  foo: bar