{{- if .Values.imagePullSecrets -}}
{{- $namespace := include "<CHARTNAME>.namespace" . -}}
{{- range .Values.imagePullSecrets -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
data:
  .dockerconfigjson: {{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .registry (printf "%s:%s" .username .password | b64enc) | b64enc }}
---
{{ end }}
{{ end }}