apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "<CHARTNAME>.namespace" . }}
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "<CHARTNAME>.name" . }}
    helm.sh/chart: {{ include "<CHARTNAME>.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name | default "http" }}
      protocol: {{ .protocol | default "TCP" }}
      port: {{ .port }}
      {{ with .targetPort -}}targetPort: {{ . }}{{- end -}}
      {{ with .nodePort -}}nodePort: {{ . }}{{- end -}}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "<CHARTNAME>.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: None
